spring:
  application:
    name: pos-products
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aw2022
    username: root
    password: 191820091
  main:
    web-application-type: reactive
server:
  port: 1145
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka